name: 'release'

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: SebRollen/toml-action@v1.0.1
        id: read_version
        with:
          file: 'src-tauri/Cargo.toml'
          field: 'package.version'
      - run: echo ${{steps.read_version.outputs.value}}
#      - name: setup rust
#        uses: dtolnay/rust-toolchain@stable
#      - name: setup tauri cli
#        run: cargo install tauri-cli
#      - name: setup yarn deps
#        run: yarn
#      - name: compile
#        run: cargo tauri build

#      - name: upload binaries to release
#        uses: softprops/action-gh-release@v1
#        if: ${{startsWith(github.ref, 'refs/tags/') }}
#        with:
#          files: |
#            src-tauri/target/release/curses.exe
#            src-tauri/target/release/bundle/msi/curses_0.0.9_x64_en-US.msi
